version: '3.8'

services:
  app:
    build: .
    container_name: movie-app
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/moviesdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_REDIS_HOST: redis
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: movie-postgres
    environment:
      POSTGRES_DB: moviesdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: movie-redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
